# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Podcast Theme
email: ben@bensanders.me
description: > # this means to ignore newlines until "baseurl:"
  An open-source Jekyll theme centered around a podcast website. Design inspired
  by starburns.audio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bensanders.me" # the base hostname & protocol for your site
twitter_username: thebensanders
github_username:  bensanders
# Build settings
markdown: kramdown
